spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 5eb3d4f9127d6e292385
            clientSecret: 34cbfc4d0a01127ad9ea6d341c29a9d6808a4b5e
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
    provider:
      github:
        authorization-uri: https://github.com/login/oauth/authorize
        token-uri: https://github.com/login/oauth/access_token
        user-info-uri: https://api.github.com/user